### PR TITLE
Add a search box with duck duck go

### PR DESCRIPTION
**Pull request by viktor-evdokimov**
So that I can keep browser in full screen mode.

### CODE REVIEW

**Comment by karakanb** [comment]
Hi Viktor, thanks for working on this. Would you mind sharing the reasoning why do you think this is needed within the extension? I am not very familiar with using browsers in full-screen mode, therefore I have always been searching for something through the browser address bar, but apparently this is not applicable for you.

In case of having this as a feature, I am reluctant since I am trying to keep the extension as clean as possible with not many additional features, so I'd be willing to have this feature in the release only if we could put this behind a feature toggle through the settings. Would you like to work on something like that?

**Comment by viktor-evdokimov** [comment]
I think feature flag make sense!
let me give it a shot

**Comment by karakanb** [comment]
Glad to hear, let me know if you need any hand. I think instead of building a custom UI we can leverage Options pages both [Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Options_pages) and [Chrome](https://developer.chrome.com/extensions/options#write_page) support, might help building this much faster and without any runtime code.

**Comment by karakanb** [comment]
Hi Viktor,

I have decided not to support this feature as of now, therefore I'll be closing this PR. Thanks for your contribution here.

**Pull request closed without merging**
