### PR TITLE
Add 12-hour support

### PR DESCRIPTION
**Pull request by Ghosts**
Hey, awesome new tab page (been using it today and really enjoying it). The only thing that was bothering me was having 12-hour time instead of 24-hour. 

Hopefully this is something that you'd find useful in it, I decided not to include am/pm to avoid changing too much code, but that could easily be done if wanted.

Love devo though! Keep up the good work.

### CODE REVIEW

**Comment by karakanb** [comment]
Hey, thank you very much for the PR!

I haven't checked how it looks and behaves yet, but I have been thinking about how best to collect this information in the page. My concern is, I aim Devo to be as simple as possible in terms of both usage and look, therefore there is always the risk of cluttering the UI. One idea I had to prevent this was to collect these configuration setup into a simple menu that can be opened from the bottom right and would contain all the switches and configuration and stuff, but that seems like a little bit of work compared to this one.

Also, as far as I can see from the PR changes, it seems like the toggle is shown as `12 o-- 24`, which doesn't have any indication about the purpose of the switch, and including 12-24 text only may not be easily understandable. Honestly, I don't have any idea how we would best indicate that this is a time format change, but this way seems not to be the best way. One thing we can do maybe is to move the hour toggle to next to hour itself where it would only be visible on hover; that way it would be much easier to understand that it is changing the hour format while keeping the UI clean.

Again, I haven't checked how it looks yet, and will definitely do. I like the idea and I think we should include this in Devo, but I believe we should do it in a way that we both/all agree that it is the best way to show this information. Thank you very much for the PR again.

**Comment by Ghosts** [comment]
No problem! I was trying to figure out the easiest way as well, the other option I thought of was clicking the time itself would flip the format (12/24) but it wouldn't necessarily be understood by a user that the feature would be there.

I like the idea of a settings menu, and it would open up the possibility to more easily expand settings. Probably just a little gear icon with a modal on click?

**Comment by karakanb** [comment]
Exactly, a gear icon that shows you a small popup menu in the corner and all the configuration living inside. That way we may be able to configure whether to show AM/PM, and the date format as well, even the language choices at some point maybe.

**Comment by Ghosts** [comment]
Is that something you'd want help working on? I'd be more than happy to help with any features/bugs.

**Comment by karakanb** [comment]
That would be great actually, I am open to any help and I didn't have much time recently to add new features, so that would be perfect if you are willing to work on that, and I'd try to support you as much as I can. 

One caveat to think about though, if you plan to work on a feature or a bug, let's make sure we are aligned before you start working. There are a few hundred users of the extension, and I would like to keep the quality of the extension high in order to keep people happy & the extension useful, which means a specific implementation or effort spent on it does not guarantee that a PR will be merged / go live. Therefore, if you plan to help improving Devo, it would be the best to discuss everything we need to discuss in an issue before any work is done in order to align regarding the features and fixes.

Overall, I would be glad to keep this project as a product of collaborative effort and I am really happy to hear you are willing to help as well. There were a few PRs that fixed some bugs and improved the overall experience and it was an amazing experience for me. As long as we keep the communication going, I am in.

**Comment by karakanb** [comment]
I am closing this PR due to inactivity. Feel free to open it back or open a new PR if you have anything new.

**Pull request closed without merging**
